[project]
name = "DragonTree"
version = "0.0.2-alpha"
description = "The programming language written in Python 3.14."
readme = "README.md"
license = "MIT"
requires-python = ">=3.14"
dependencies = []
